import { 
  Calendar, 
  DollarSign, 
  Users, 
  Clock, 
  BarChart3, 
  Zap,
  Settings,
  LogOut,
  Menu,
  X,
  Plus,
  Search,
  Bell,
  User,
  Home,
  TrendingUp,
  AlertCircle,
  CheckCircle,
  XCircle,
  Loader2,
  Power,
  Sparkles,
  Rocket,
  Target,
  Eye,
  EyeOff,
  Mail,
  Lock,
  ArrowRight,
  Download,
  Share2,
  Copy,
  Trash2,
  Edit,
  MoreVertical,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  PieChart,
  Activity,
  Cpu,
  Brain,
  Award,
  Flame,
  Crown,
  MessageCircle,
  RefreshCw,
  Grid,
  HelpCircle
} from 'lucide-react';

// Export all icons as a single object
export const Icons = {
  calendar: Calendar,
  dollar: DollarSign,
  users: Users,
  clock: Clock,
  chart: BarChart3,
  zap: Zap,
  settings: Settings,
  logout: LogOut,
  menu: Menu,
  close: X,
  plus: Plus,
  search: Search,
  bell: Bell,
  user: User,
  home: Home,
  trendingUp: TrendingUp,
  alert: AlertCircle,
  success: CheckCircle,
  error: XCircle,
  loading: Loader2,
  power: Power,
  sparkles: Sparkles,
  rocket: Rocket,
  target: Target,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  lock: Lock,
  arrowRight: ArrowRight,
  download: Download,
  share: Share2,
  copy: Copy,
  trash: Trash2,
  edit: Edit,
  more: MoreVertical,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  pieChart: PieChart,
  activity: Activity,
  cpu: Cpu,
  brain: Brain,
  award: Award,
  flame: Flame,
  crown: Crown,
  messageCircle: MessageCircle,
  refresh: RefreshCw,
  grid: Grid,
  helpCircle: HelpCircle
};

// Simple icon wrapper component
export const Icon = ({ name, size = 20, className = "" }) => {
  const IconComponent = Icons[name];
  if (!IconComponent) {
    return <span className={className} style={{ fontSize: size }}>•</span>;
  }
  return <IconComponent size={size} className={className} />;
};